# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'CJProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CJProject
    pod 'SnapKit'
    pod 'Kingfisher'

    # banner滚动图片
    pod 'FSPagerView'

    # 数据处理
    pod 'Moya'
    pod 'HandyJSON', '~> 4.2.0'
    pod 'SwiftyJSON'
    
    pod 'DNSPageView'


end
